### ISSUE TITLE
Https on sharing url

### ISSUE THREAD

**Issue by x011** [bilde2910/Hauk#136] opened 2020-05-18 15:05 UTC
Hi there,

Thank you for the time and knowledge you've put into this project.

`Hawk` ignores if the server is using `https` and always creates the share link in `http`. 
Can you update it so it takes `https` in consideration and creates  the share url accordingly?

Thank you.

**Comment by licaon-kter** [comment] 2020-05-18 15:37
/close as duplicate https://github.com/bilde2910/Hauk/issues/129

Did you lose your issue?

**Comment by bilde2910** [comment] 2020-05-18 22:02
Duplicate of #129. Please re-open that issue if the suggested fix from #129 does not work.

**Closed by bilde2910** 2020-05-18 22:02 UTC
