### ISSUE TITLE
Host www.example.com cannot be found, while host does exist

### ISSUE THREAD

**Issue by gnusupport** [bilde2910/Hauk#126] opened 2020-01-24 08:55 UTC
I would not like sharing here the host name, however message says:

Connection Error

Unable to resolve host "www.example.com": No address associated with hostname -- even though hostname is easily resolvable, and I can see in browser Point the Hauk app to this server to share your location: https://www.example.com/files/hauk/

What can be the error?

Can CNAME record for www.example.com that points to example.com be the problem?

**Comment by licaon-kter** [comment] 2020-01-24 09:36
What does logcat say?

**Comment by bilde2910** [comment] 2020-01-25 12:09
That's very strange. Could you try re-typing the URL? Most likely this is due to some typo that may or may not be easily spotted. You could try copy-pasting the server URL from Hauk and open it in a browser on your phone to verify if your browser can open it exactly as copied. Or copy the "Point the Hauk app to this server" URL back into the Hauk app and see what happens.

CNAME records should not affect resolution in any way.

**Comment by bilde2910** [comment] 2020-03-04 11:48
Is this still applicable? I'm just looking through old unresolved issues and will close it if you figured it out. :-)

**Comment by bilde2910** [comment] 2020-06-06 14:59
Closing - unable to reproduce, and no response from reporter.

**Closed by bilde2910** 2020-06-06 14:59 UTC
