### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#151] opened 2020-07-15 09:26 UTC
Now for a 300sec interval I got even 20mins of no updates (#150), so I need to kill the app and restart it (so it continues the sharing).

This feels combersome and odd, if the app can just resetup everything (keeping the same link, very important), please allow this in the interface proper.

**Comment by bilde2910** [comment] 2020-07-30 18:28
The app failing to push updates is not expected behavior. I don't feel a manual refresh button would be the best approach. Preferably fixing the root cause of #150, or if a root cause cannot be identified, some automatic background task that forces the location listener to stay alive. As this would be fixed by #150 and shares root cause, I will mark this as duplicate.

**Closed** 2020-07-30 18:28 UTC
Labels: duplicate
