### ISSUE TITLE
Outdated for android 13

### ISSUE THREAD

**Issue by nixbits** [bilde2910/Hauk#198] opened 2023-08-06 19:27 UTC
Today I tried to install via google play. It was not available for the current android release.
The message was that, the current 1.6.1 Hauk version was made for an older android version.

**Comment by licaon-kter** [comment] 2023-08-07 03:50
And there was no "more info" button? If you pressed that button there was no "install anyway"?

**Comment by licaon-kter** [comment] 2023-08-07 03:51
/close as duplicate #191

Maybe fixed by #193

Still available in F-Droid ;)

**Comment by nixbits** [comment] 2023-08-07 04:11
> And there was no "more info" button? If you pressed that button there was no "install anyway"?

Nothing. I had to install it from a usb pen.

**Comment by rustyduffer** [comment] 2023-08-11 20:26
This problem is also causing me huge issues! I have been using Hauk to help coordinate charity volunteers and now many of them are unable to use the app :(

**Comment by licaon-kter** [comment] 2023-08-11 20:38
@rustyduffer are the steps written above unhelpful?

**Comment by rustyduffer** [comment] 2023-08-11 20:43
@licaon-kter oh I didn't see that!

Hmm so it only works if you install it from F-Droid?

That's good, but the people I work with are not tech-savvy and trying to get them to use a different app store will not be possible I fear :(

**Comment by bilde2910** [comment] 2023-08-11 21:18
If all goes well, I'll be pushing an update by the end of the weekend. My plan for updating it during the weekdays after work was foiled due to some unexpected things that came up. But this weekend I have no plans scheduled.

-------- Original Message --------

**Comment by rustyduffer** [comment] 2023-08-11 21:21
You're the best! You're doing great work providing self-hosted ungoogled geolocation software

**Comment by licaon-kter** [comment] 2023-08-11 21:53
> Hmm so it only works if you install it from F-Droid?

I don't know your friends issue exactly, while `It was not available for the current android release.` is a symptom we see for APKs installed from elsewhere, I never saw a picture of such a message when one tries to install from Play.

**Comment by rustyduffer** [comment] 2023-08-11 21:58
@licaon-kter at least five people reported the same issue today when I was talking them through how to install Hauk.

One of them sent me a Google Play screenshot which showed the error "This app isn't available because it was made for an older version of Android"

I'm on a custom ROM and also using F-Droid so I can't replicate the problem. But 5+ people all reported the same issue today so I highly doubt it's just user error

**Comment by licaon-kter** [comment] 2023-08-12 03:47
@rustyduffer I didn't say "user error", just trying to find a way for them to fix it

Also, there's no bad time to _start using F-Droid_ :)

**Comment by bilde2910** [comment] 2023-08-13 14:21
I've just uploaded a new APK that targets Android 13. The APK has also been provided to Google Play for review. I believe F-Droid will automatically build the APK at some point (I can't recall exactly how the F-Droid publishing process works right now).

One unfortunate change is that incompatibilities with assets (specifically the use of references to colors in image assets) has caused the app to no longer support Android 6. As of now, Android 7 is the lowest supported Android version. Hopefully I'll be able to find some workaround for this that allows me to target Android 6 again in the future.

The release is also available on the [releases page](https://github.com/bilde2910/Hauk/releases/tag/v1.6.2) for manual installation.

**Closed by bilde2910** 2023-08-13 14:21 UTC

**Comment by licaon-kter** [comment] 2023-08-13 14:51
F-Droid will pickup and build, yes.

I guess the recipe needs to update to use Java17, will update asap.

**Comment by bilde2910** [comment] 2023-08-13 17:42
v1.6.2 should now be available on Google Play. I can confirm that I am able to install it from there on an Android 13 device.

**Comment by licaon-kter** [comment] 2023-08-14 06:36
Done https://gitlab.com/fdroid/fdroiddata/-/commit/1f92cb10f6c2072b7df9abb48f10e5564f748b16 so will be built next cycle
